development:
  adapter: mysql2
  encoding: utf8
  database: hrms_homepage_development
  pool: 5
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: hrms_homepage_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: hrms_homepage_production
  pool: 5
  username: root
  password: theadroit
  socket: /var/run/mysqld/mysqld.sock
